### ISSUE TITLE
Starting delayed job in production environment not working

### ISSUE THREAD

**Issue by ChunAllen** [AgileConsultingLLC/capistrano3-delayed-job#14]
I'm using capistrano3 and this gem for delayed job in production. When I deployed to production environment using `cap production deploy` here's the screenshot of the capistrano log

<img width="972" alt="screenshot 2018-01-10 16 57 01" src="https://user-images.githubusercontent.com/2100728/34763783-4c14be20-f627-11e7-88f0-d8c9b811890e.png">

it should restart the delayed job worker but it's not running. The workaround I did was to run 

```
RAILS_ENV=production bin/delayed_job restart
```

in the root directory of my current application. 

Any solutions with this?

**Comment by rab** [comment]
That certainly *looks* like there are 2 workers (with PIDs 7871 and 7887) running after the restart.

Why do you say that the worker is not running?

**Comment by ChunAllen** [comment]
@rab I checked the jobs in delayed job web it's still in pending/enqueued and not running, but if I do the `RAILS_ENV=production bin/delayed_job start` 
then it will run

**Comment by ChunAllen** [comment]
Every time I deploy using capistrano I can see that there's a `delayed_job:restart` task which basically runs the `bundle exec bin/delayed_job -n 5 --queues=mailer,tracking --prefix=reports restart`

<img width="963" alt="screenshot 2018-01-31 12 10 52" src="https://user-images.githubusercontent.com/2100728/35604898-ce561ca4-067f-11e8-9fd6-86ffe09248d5.png">


But is it running the workers with environment? I think it's not running workers in a specific environment because my jobs are just pending

**Comment by rab** [comment]
If you look at `bin/delayed_job`, you'll see that it loads (`require`s actually) your `config/environment` file.

When your jobs are pending, can you open a console and run: `pp Delayed::Job.all` to see what `queue` each job is placed in? (If you have lots of jobs, it should be enough to do `Delayed::Job.group(:queue).count` and see job counts by queue.

Are the jobs being queued to the `mailer` or `tracking` queues that your command is telling them to look for? (Note that the default is to get the _next_ job without regard to the queue.)

You can also "manually" run the jobs with `rails delayed_job:workoff` to see some of the job details as they are processed.

**Comment by rab** [comment]
Lacking any further response, I'm assuming that your problem was solved or wasn't actually a _problem_.
