### ISSUE TITLE
Deploy errors with "Aborted" on RHEL/CentOS

### ISSUE THREAD

**Issue by kule** [AgileConsultingLLC/capistrano3-delayed-job#16]
Hope you don't mind me adding this here (can be closed immediately).  I spent a fair bit of time trying to find what was causing this so putting this here as it's probably one of the first places people will look...

Cap deploys fail at when restarting delayed job - you'll get something like:

```
-> RAILS_ENV="production" bundle exec bin/delayed_job -n 1 --pool='mailer:1' --pool='*:1' restart
delayed_job.0: trying to stop process with pid 12584...
delayed_job.0: process with pid 12584 successfully stopped.
delayed_job.0: process with pid 12883 started.
delayed_job.1: trying to stop process with pid 12590...
delayed_job.1: process with pid 12590 successfully stopped.
delayed_job.1: process with pid 12900 started.
Aborted
```

This is due to an issue with ffi ```bundle update ffi``` so you have version >= 1.9.25 will fix it - related link: https://github.com/ffi/ffi/issues/621

**Comment by rab** [comment]
Thanks for this. I'm actually going to leave it open for a while so people who search will find it.
