### ISSUE TITLE
You need to add gem 'daemons' to your Gemfile

### ISSUE THREAD

**Issue by vedant1811** [AgileConsultingLLC/capistrano3-delayed-job#3]
After setting up as written in README and running `cap deploy` I got the following error:

    You need to add gem 'daemons' to your Gemfile if you wish to use it

Naturally, adding it solved the error.

It would be great if this gem is listed as a dependency.

**Comment by rab** [comment]
I don't think that this is a dependency of `capistrano3-delayed-job` but of something else in your project. (It's not an *error*, but just a notice, I think.)

**Comment by simonknoll** [comment]
I would say it is related: https://github.com/collectiveidea/delayed_job#running-jobs
It won't work without it but one could argue that this should be integrated within the delayed_job gem itself. Anyways it would be great if this dependency could be added to this gem, as it will obviously not work without it.

**Comment by rab** [comment]
Ok @simonknoll , your pointer to the delayed_job docs has convinced me to make this a direct dependency. A new version will be out soon.

**Comment by simonknoll** [comment]
Thanks a lot @rab for fixing it! 👍
