### ISSUE TITLE
Error during deploy

### ISSUE THREAD

**Issue by gregblass** [AgileConsultingLLC/capistrano3-delayed-job#6]
Greetings!

Not many issues here, but I'm hoping someone might be able to help out.

I'm getting this error after installing the gem:
```

/usr/bin/env sudo service delayed_job_(appname)_production restart

 DEBUG [ffd7835a] 	sudo

 DEBUG [ffd7835a] 	: 

 DEBUG [ffd7835a] 	no tty present and no askpass program specified

 DEBUG [ffd7835a] 	
```

Wondering if anyone has any clue why that might happen? I'm not using PTY, I've got my deploy user set up to work through an SSH key.

**Comment by rab** [comment]
This isn't really an issue for the gem, but I'll say that you probably need to set up an entry in your `sudoers` file similar to:

```
Cmnd_Alias DELAYED_JOB = service delayed_job_(appname)_production restart
deployuser ALL = NOPASSWD: DELAYED_JOB
```

I'm going to close this and direct you to the "Authorisation" section of http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/

**Comment by u007** [comment]
why cant it be bundle exec delayed_job:work ?
or bin/delayed_job start -n x ?
