### ISSUE TITLE
Problem with permissions on the binary

### ISSUE THREAD

**Issue by jeanfbrito** [AgileConsultingLLC/capistrano3-delayed-job#8]
I taked alot of time to get rid of it. On deploy capistrano was giving this error:

> SSHKit::Command::Failed: bundle exit status: 126
bundle stdout: bundler: not executable: bin/delayed_job
bundle stderr: Nothing written

I'm really a newbie and this put me down in deploying. 
The solution was to add a chmod to the deploy:

`task :chmod_delayed_jobs do
  on roles(:all) do
    execute "chmod +x #{current_path}/bin/delayed_job "
  end
end
after "passenger:restart", "chmod_delayed_jobs"`

![image](https://user-images.githubusercontent.com/1177482/28240832-ce58484e-695e-11e7-9e1a-e0f428b6f300.png)

Then it started working. I think that this gem needs to get around this problem. Could you help to resolve this issue inside the gem, without needing to change the permissions on a task?
I'm using DigitalOcean Ubuntu 16.04 and following the GoRails tutorial.

Sorry, I dont know to style the ruby code to work here.

**Comment by rab** [comment]
Did you try changing the executable flag on your local copy of `bin/delayed_job` and committing that to the repository before you deploy?

Also, *from* what type of system are you deploying?

**Comment by rab** [comment]
Since file permissions are maintained inside a `git` repository, if this is something that *you* need to do because your deployment strategy doesn't maintain permissions, a local fix is more appropriate.
